trigger:
- master
pool:
  vmImage: 'Ubuntu-18.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'hts2-accesstoken'
    cliInstallationRepo: 'cli-old'

- task: JFrogDocker@1
  inputs:
    command: 'Pull'
    artifactoryConnection: 'hts2-accesstoken'
    imageName: 'hts2-jana-docker-virtual.jfrog.io/nginx:latest'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    skipLogin: false

- task: JFrogDocker@1
  inputs:
    command: 'Push'
    artifactoryConnection: 'hts2-accesstoken'
    imageName: 'hts2-jana-docker-virtual.jfrog.io/nginx:latest'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    threads: '3'
    skipLogin: false'